---

- name: Configure cluster proxy in meteor
  set_fact:
    bbb_meteor: "{{ bbb_meteor | default({}) | combine(bbb_proxy_meteor, recursive=True) }}"
  when: bbb_proxy_host is defined

- name: Write custom meteor config
  become: true
  copy:
    content: "{{ bbb_meteor | to_nice_yaml(indent=2) }}"
    dest: /etc/bigbluebutton/bbb-html5.yml
    mode: "0644"
  notify:
    - Restart bbb-html5

- name: Enable sipjsHackViaWs
  replace:
    path: /usr/share/bigbluebutton/nginx/sip.nginx
    regexp: proxy_pass .*
    replace: proxy_pass http://{{ bbb_freeswitch_ip_address }}:5066;
  when: ((((bbb_meteor | default({})).public | default({})).media | default({})).sipjsHackViaWs  | default({})) | bool
  notify: Reload nginx

- name: Disable sipjsHackViaWs
  replace:
    path: /usr/share/bigbluebutton/nginx/sip.nginx
    regexp: proxy_pass .*
    replace: proxy_pass https://{{ bbb_freeswitch_ip_address }}:7443;
  when: not ((((bbb_meteor | default({})).public | default({})).media | default({})).sipjsHackViaWs  | default({})) | bool
  notify: Reload nginx

- name: Set loadbalancer.nginx for the cluster proxy
  ansible.builtin.copy:
    dest: "/usr/share/bigbluebutton/nginx/loadbalancer.nginx"
    content: "set $bbb_loadbalancer_node https://{{ bbb_proxy_host }};"
    mode: "0644"
  when: bbb_proxy_host is defined
  notify: Reload nginx

- name: Set bbb-html5.nginx for the cluster proxy
  ansible.builtin.replace:
    path: /usr/share/bigbluebutton/nginx/bbb-html5.nginx
    regexp: 'location (/[^/]+)?/html5client'
    replace: "location /{{ bbb_proxy_name }}/html5client"
  when: bbb_proxy_host is defined
  notify: Reload nginx

- name: Increase max-old-space-size in frontends
  become: true
  replace:
    path: /usr/share/meteor/bundle/systemd_start_frontend.sh
    regexp: (--max-old-space-size)=(\d*)
    replace: \1={{ bbb_html5_frontend_max_old_space_size }}
  notify:
    - Restart bbb-html5

- name: Set amount of html5 back- and frontends
  become: true
  template:
    src: bbb-html5/bbb-html5-with-roles.conf
    dest: /etc/bigbluebutton/bbb-html5-with-roles.conf
    mode: "0644"
  notify:
    - Restart bbb-web

- name: Setup html5-frontend nginx connections
  template:
    src: nginx/bbb-html5-loadbalancer.conf.j2
    dest: /etc/nginx/conf.d/bbb-html5-loadbalancer.conf
    mode: "0644"
  notify: Reload nginx
